# Generated by Django 3.2.19 on 2024-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_de_salud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='diagnostico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='estudio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='dosis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='droga',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='prospecto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
